---
swagger: "2.0"
info:
  version: "1.0"
  title: "marek-rocks-lambda"
host: "marek.rocks"
schemes:
- "https"
paths:
  /:
    get:
      responses: {}
  /{proxy+}:
    x-amazon-apigateway-any-method:
      produces:
      - "application/json"
      parameters:
      - name: "proxy"
        in: "path"
        required: true
        type: "string"
      responses: {}
